---
Author: "Anna Ramji"
Date: 2024-01-10
---

# Week 1 Discussion:
**Practicing cleaning, wrangling, annotating**

## Load packages

```{r}
library(tidyverse)
library(usdata)
library(here)
```

## Read in data
```{r}
fracking_raw <- read_csv(here("week1", "data", "fracking.csv"))

```

## Preliminary exploration
```{r}
head(fracking_raw)

```
Yuck! super messy. We have inconsistent CamelCase in the column names, inaccurate datatypes for data stored in columns (stored as characters, not datetime objects; some numbers stored as characters). 


# Cleaning


```{r}
#fracking_cleaned <- fracking_raw |> 
 # janitor::clean_names() |>  # tidying column names
  
  

#head(fracking_cleaned)
```


```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)
library(janitor)
library(usdata)

#......................import fracking data......................
fracking <- read_csv(here::here("week1", "data", "fracking.csv"))

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                        clean/wrangle fracking data                       ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

fracking_clean <- fracking |> 
  
  # clean column names ----
  janitor::clean_names() |> # update column names to lower_snake_case
  
  # clean up dates ----
  mutate(job_start_date = str_remove(job_start_date, " AM")) |> # remove " AM" from the job_start_date column
  mutate(datetime_start = mdy_hms(job_start_date)) |> # convert job_start_date from string to datetime object (save to new col datetime_start)
  mutate(year = year(datetime_start)) |> # create 'year' col from datetime_start

  # select relevant cols ----
  select(datetime_start, year, state_name, county_name, well_name, total_base_water_volume) |> 
  
  # filter out non-state names ----
  filter(!state_name %in% c("Beaver", "Beckham", "Harper", "Hemphill", "Midland", "Red River", "Roosevelt", "Rusk", "State", "WARD")) |> # filter out names in the state_name column that are not state names
  
  # rename state_name to something shorter for typing out when using case_when (not necessary) ----
  rename(sn = state_name) |> # renaming state_name to "sn" for ease of typing in our case_when step below
  
  # make all words title case ----
  mutate(sn = str_to_title(sn)) |> # making sn column Title Case
  
  # fix misspelled state names ----
# syntax:
# sn == "misspelled state name" ~ "correct state name
  mutate(sn = case_when( 
    sn == "Colordao" ~ "Colorado",
    sn == "Loiusiana" ~ "Louisiana",
    sn == "Louisianna" ~ "Louisiana",
    sn == "Lousiana" ~ "Louisiana",
    sn == "New Mexcio" ~ "New Mexico",
    sn == "Norh Dakota" ~ "North Dakota",
    sn == "Norht Dakota" ~ "North Dakota",
    sn == "North  Dakota" ~ "North Dakota",
    sn == "North Dakata" ~ "North Dakota",
    sn == "North Dakotta" ~ "North Dakota",
    sn == "Noth Dakota" ~ "North Dakota",
    sn == "Pennslvania" ~ "Pennsylvania",
    sn == "Pennsylavania" ~ "Pennsylvania",
    sn == "Pennsylvanya" ~ "Pennsylvania",
    sn == "Penssylvania" ~ "Pennsylvania",
    sn == "Texasa" ~ "Texas",
    sn == "Texs" ~ "Texas", 
    sn == "West Viginia" ~ "West Virginia",
    sn == "Wyominng" ~ "Wyoming", 
    TRUE ~ sn # copy over the rest of state names from sn column as-is
  )) |> 
  
  # remove rows that have a '?' mark ----
  filter(!str_detect(string = sn, pattern = "\\?")) |> # `?` is a special character; escape with `\\` prefix (remember: LaTeX)
  
  # make all uppercase (so that we can convert abbreviation to state names) ----
  mutate(sn = str_to_upper(sn)) |> 
  
  # mutate abbreviations to full state names ----
  mutate(sn = ifelse(test = str_length(sn) == 2, # if string in 'sn' col is 2 chrs long (logical)
                     yes = usdata::abbr2state(sn), # replace abbreviation with full state name 
                     no = sn)) |> # if string in 'sn' col is not 2 chrs long, keep state name as-is
  # basically making 2-character long (already abbreviation format) values into full state names
  
  # make all words title case again ----
  mutate(sn = str_to_title(sn)) |> 
  
  # create a column of just state abbreviations ----
  mutate(state_abb = usdata::state2abbr(sn)) |> # make new column "state_abb" with state abbreviations
  
  # rename 'sn' to 'state_name' again for clarity ----
  rename(state_name = sn, # revert to old name for clarity
         total_base_water_volume_gal = total_base_water_volume) |> # adding units (gallons)
  
  # move 'state_abb' col after state_name col ----
  relocate(state_abb, .after = state_name) |> 
  
  # convert 'state_name' & 'state_abb' from string to factor ----
  mutate(state_name = as.factor(state_name),
         state_abb = as.factor(state_abb)) |> 
  
  # remove obs that don't have a measurement for 'total_base_water_volume_gal' (NA) ----
  drop_na(total_base_water_volume_gal)

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##          some exploratory data viz + a few plot mods for practice        ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

fracking_clean |> 
  filter(state_name %in% c("Texas", "Colorado", "North Dakota")) |> 
  filter(year == 2015) |> 
  group_by(state_name) |> # pipe directly into ggplot
  ggplot(aes(x = fct_rev(fct_infreq(state_name)), y = total_base_water_volume_gal)) + # need to reverse fct order for coord_flip() (plots lowest freq at top by default)
  geom_jitter(width = 0.3, alpha = 0.5, color = "gray15") +
  geom_violin(color = "red4", alpha = 0.3) +
  scale_y_continuous(labels = scales::label_comma()) +
  labs(y = "Total base water volume (gal)") +
  coord_flip() +
  theme_minimal() +
  theme(
    axis.title.y = element_blank()
    ) 
```

