---
Author: "Anna Ramji"
Date: 2024-01-22
---


run to install required packages

```{r , eval=FALSE, message=FALSE}
install.packages("chron") # for working with dates / times
install.packages("naniar") # tools for exploring & handing missing data
install.packages("tidytuesdayR") # used to download TidyTuesday data
install.packages("tidycensus") # an R package that allows users to interface with a select number of the US Census Bureau’s data APIs and return tidyverse-ready data frames
install.packages("ggridges") # {ggplot2} extension for creating ridgeline plots
install.packages("gghighlight") # {ggplot2} extension for highlighting geoms
install.packages("ggbeeswarm") # {ggplot2} extension for creating categorical scatter (violin point) plots
install.packages("see") # {ggplot2} extension for model visualization (we'll be using it for it's geom, geom_violindot())
install.packages("scales") # provides the internal scaling infrastructure used by ggplot2, and gives you tools to override the default breaks, labels, transformations and palettes (installed automatically with {ggplot2} or {tidyverse})
```

library of packages

```{r library, message=FALSE}
library(tidyverse)
library("chron") # for working with dates / times
library("naniar") # tools for exploring & handing missing data
library("tidytuesdayR") # used to download TidyTuesday data
library("tidycensus") # an R package that allows users to interface with a select number of the US Census Bureau’s data APIs and return tidyverse-ready data frames
library("ggridges") # {ggplot2} extension for creating ridgeline plots
library("gghighlight") # {ggplot2} extension for highlighting geoms
library("ggbeeswarm") # {ggplot2} extension for creating categorical scatter (violin point) plots
library("see") # {ggplot2} extension for model visualization (we'll be using it for it's geom, geom_violindot())
library("scales") # provides the internal scaling infrastructure used by ggplot2, and gives you tools to override the default breaks, labels, transformations and palettes (installed automatically with {ggplot2} or {tidyverse})
```

source script from KEYS.R

```{r}
source(here::here("week3", "KEYS.R"))
```

read in data

```{r}


```
